# name: Build and Test Next JS App

# on:
#   push:
#     branches:
#       - 'main'

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: 20

#     - name: Install npm dependencies
#       run: npm install

#     - name: Build Next JS App
#       run: npm run build 

#     # - name: Run GitLeaks Scan
#     #   run: |
#     #     wget https://github.com/zricethezav/gitleaks/releases/download/v7.6.0/gitleaks-linux-amd64
#     #     chmod +x gitleaks-linux-amd64
#     #     ./gitleaks-linux-amd64 -o gitleaks-report.json

#     # - name: Build Docker image
#     #   run: docker build -t sco-ui .

#     # - name: Run Tests
#     #   run: npm test 

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v4
#       with:
#           # role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
#           aws-region: us-west-2

#     - name: Login to Amazon ECR
#       id: login-ecr
#       uses: aws-actions/amazon-ecr-login@v2

#     - name: Build, tag, and push docker image to Amazon ECR
#       env:
#           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           REPOSITORY: simpleproject
#           IMAGE_TAG: ${{ github.sha }}
#       run: |
#           docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
#           docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG    








name: Dev Pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  dev-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run GitLeaks Scan
      run: |
        wget https://github.com/zricethezav/gitleaks/releases/download/v7.6.0/gitleaks-linux-amd64
        chmod +x gitleaks-linux-amd64
        ./gitleaks-linux-amd64 -o gitleaks-report.json  

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install npm dependencies
      run: npm install

    - name: Code Lint Check
      run: npm run lint

    - name: Update Env
      run: cp .env.dev .env

    - name: Build Docker image
      run: docker build -t sco-ui .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_SECRET_KEY }}
          aws-region: us-east-1

    - name: Docker Tag and Push
      run: |
              aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 
              311544399277.dkr.ecr.us-east-1.amazonaws.com
              docker tag frontendnext:latest 311544399277.dkr.ecr.us-east-1.amazonaws.com/frontendnext:latest
              docker tag frontendnext:latest 311544399277.dkr.ecr.us-east-1.amazonaws.com/frontendnext:build-${{ github.run_id }}
              docker push 311544399277.dkr.ecr.us-east-1.amazonaws.com/frontendnext:latest
              docker push 311544399277.dkr.ecr.us-east-1.amazonaws.com/frontendnext:build-${{ github.run_id }}




