name: PR Action Pipeline

on:
  pull_request:
    branches:
      - '**'

jobs:
  pr-action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    
    - name: Run GitLeaks Scan
      run: |
        wget https://github.com/zricethezav/gitleaks/releases/download/v7.6.0/gitleaks-linux-amd64
        chmod +x gitleaks-linux-amd64
        ./gitleaks-linux-amd64 -o gitleaks-report.json

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install npm dependencies
      run: npm install

    - name: Code Lint Check
      run: npm run lint

    - name: Build Docker image
      run: docker build -t sco-ui .  

    # - name: Run Tests
    #   run: npm test 
    
